/*
 * Secrets Manager
 * API to access the Secrets Manager
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intirix.secretsmanager.clientv1.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Secret
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-04T11:05:51.227Z")
public class Secret {
  @SerializedName("sid")
  private String sid = null;

  @SerializedName("hmac")
  private String hmac = null;

  @SerializedName("hmacKey")
  private String hmacKey = null;

  @SerializedName("encryptedSecret")
  private String encryptedSecret = null;

  @SerializedName("secretEncryptionProfile")
  private String secretEncryptionProfile = null;

  @SerializedName("users")
  private Object users = null;

  public Secret sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Unique Secret ID
   * @return sid
  **/
  @ApiModelProperty(value = "Unique Secret ID")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Secret hmac(String hmac) {
    this.hmac = hmac;
    return this;
  }

   /**
   * keyed-hash message authentication code for the secret
   * @return hmac
  **/
  @ApiModelProperty(value = "keyed-hash message authentication code for the secret")
  public String getHmac() {
    return hmac;
  }

  public void setHmac(String hmac) {
    this.hmac = hmac;
  }

  public Secret hmacKey(String hmacKey) {
    this.hmacKey = hmacKey;
    return this;
  }

   /**
   * key used to generate the HMAC
   * @return hmacKey
  **/
  @ApiModelProperty(value = "key used to generate the HMAC")
  public String getHmacKey() {
    return hmacKey;
  }

  public void setHmacKey(String hmacKey) {
    this.hmacKey = hmacKey;
  }

  public Secret encryptedSecret(String encryptedSecret) {
    this.encryptedSecret = encryptedSecret;
    return this;
  }

   /**
   * The encrypted secret
   * @return encryptedSecret
  **/
  @ApiModelProperty(value = "The encrypted secret")
  public String getEncryptedSecret() {
    return encryptedSecret;
  }

  public void setEncryptedSecret(String encryptedSecret) {
    this.encryptedSecret = encryptedSecret;
  }

  public Secret secretEncryptionProfile(String secretEncryptionProfile) {
    this.secretEncryptionProfile = secretEncryptionProfile;
    return this;
  }

   /**
   * Encryption profile for the secret
   * @return secretEncryptionProfile
  **/
  @ApiModelProperty(value = "Encryption profile for the secret")
  public String getSecretEncryptionProfile() {
    return secretEncryptionProfile;
  }

  public void setSecretEncryptionProfile(String secretEncryptionProfile) {
    this.secretEncryptionProfile = secretEncryptionProfile;
  }

  public Secret users(Object users) {
    this.users = users;
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @ApiModelProperty(value = "")
  public Object getUsers() {
    return users;
  }

  public void setUsers(Object users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Secret secret = (Secret) o;
    return Objects.equals(this.sid, secret.sid) &&
        Objects.equals(this.hmac, secret.hmac) &&
        Objects.equals(this.hmacKey, secret.hmacKey) &&
        Objects.equals(this.encryptedSecret, secret.encryptedSecret) &&
        Objects.equals(this.secretEncryptionProfile, secret.secretEncryptionProfile) &&
        Objects.equals(this.users, secret.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sid, hmac, hmacKey, encryptedSecret, secretEncryptionProfile, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Secret {\n");
    
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    hmac: ").append(toIndentedString(hmac)).append("\n");
    sb.append("    hmacKey: ").append(toIndentedString(hmacKey)).append("\n");
    sb.append("    encryptedSecret: ").append(toIndentedString(encryptedSecret)).append("\n");
    sb.append("    secretEncryptionProfile: ").append(toIndentedString(secretEncryptionProfile)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

