/*
 * Secrets Manager
 * API to access the Secrets Manager
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intirix.secretsmanager.clientv1.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SecretUserData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-04T11:05:51.227Z")
public class SecretUserData {
  /**
   * Can the user write to the secret
   */
  @JsonAdapter(CanWriteEnum.Adapter.class)
  public enum CanWriteEnum {
    Y("Y"),
    
    N("N");

    private String value;

    CanWriteEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CanWriteEnum fromValue(String text) {
      for (CanWriteEnum b : CanWriteEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CanWriteEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CanWriteEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CanWriteEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CanWriteEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("canWrite")
  private CanWriteEnum canWrite = null;

  @SerializedName("encryptedKey")
  private String encryptedKey = null;

  public SecretUserData canWrite(CanWriteEnum canWrite) {
    this.canWrite = canWrite;
    return this;
  }

   /**
   * Can the user write to the secret
   * @return canWrite
  **/
  @ApiModelProperty(value = "Can the user write to the secret")
  public CanWriteEnum getCanWrite() {
    return canWrite;
  }

  public void setCanWrite(CanWriteEnum canWrite) {
    this.canWrite = canWrite;
  }

  public SecretUserData encryptedKey(String encryptedKey) {
    this.encryptedKey = encryptedKey;
    return this;
  }

   /**
   * The key that can decrypted the secret, encrypted by the user's private key
   * @return encryptedKey
  **/
  @ApiModelProperty(value = "The key that can decrypted the secret, encrypted by the user's private key")
  public String getEncryptedKey() {
    return encryptedKey;
  }

  public void setEncryptedKey(String encryptedKey) {
    this.encryptedKey = encryptedKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretUserData secretUserData = (SecretUserData) o;
    return Objects.equals(this.canWrite, secretUserData.canWrite) &&
        Objects.equals(this.encryptedKey, secretUserData.encryptedKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canWrite, encryptedKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretUserData {\n");
    
    sb.append("    canWrite: ").append(toIndentedString(canWrite)).append("\n");
    sb.append("    encryptedKey: ").append(toIndentedString(encryptedKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

