/*
 * Secrets Manager
 * API to access the Secrets Manager
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intirix.secretsmanager.clientv1.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
